language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "3.0"
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python comicMaker.py
